export const schemaSql = `
CREATE TABLE IF NOT EXISTS issues (
    issue_id TEXT PRIMARY KEY,
    project TEXT,
    parent_issue_id TEXT,
    title TEXT NOT NULL,
    assignee TEXT,
    sprint TEXT,
    status TEXT,
    version TEXT,
    description TEXT,
    comments JSONB,
    im_summary TEXT,
    im_solution TEXT,
    im_criteria TEXT,
    im_estimation JSONB,
    extra JSONB,
    created_at TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"')),
    updated_at TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'))
);

ALTER TABLE issues ADD COLUMN IF NOT EXISTS project TEXT;

DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = current_schema()
          AND table_name = 'issues'
          AND column_name = 'im_estimation'
          AND data_type <> 'jsonb'
    ) THEN
        EXECUTE 'ALTER TABLE issues DROP COLUMN im_estimation';
    END IF;
END $$;

ALTER TABLE issues DROP COLUMN IF EXISTS dm_summary;
ALTER TABLE issues DROP COLUMN IF EXISTS dm_solution;
ALTER TABLE issues DROP COLUMN IF EXISTS dm_criteria;
ALTER TABLE issues DROP COLUMN IF EXISTS dm_estimation;
ALTER TABLE issues DROP CONSTRAINT IF EXISTS chk_issues_im_estimation_json;

ALTER TABLE issues ADD COLUMN IF NOT EXISTS im_summary TEXT;
ALTER TABLE issues ADD COLUMN IF NOT EXISTS im_solution TEXT;
ALTER TABLE issues ADD COLUMN IF NOT EXISTS im_criteria TEXT;
ALTER TABLE issues ADD COLUMN IF NOT EXISTS im_estimation JSONB;

ALTER TABLE issues
ADD CONSTRAINT chk_issues_im_estimation_json
CHECK (
    im_estimation IS NULL
    OR (
        jsonb_typeof(im_estimation) = 'object'
        AND im_estimation ? 'development_mode'
        AND im_estimation ->> 'development_mode' IN ('agent', 'agent-led', 'human-led')
        AND im_estimation ? 'hours'
        AND jsonb_typeof(im_estimation -> 'hours') = 'number'
        AND im_estimation ? 'rationale'
        AND jsonb_typeof(im_estimation -> 'rationale') = 'string'
    )
);

CREATE INDEX IF NOT EXISTS idx_issues_issue_id ON issues (issue_id);
CREATE INDEX IF NOT EXISTS idx_issues_project ON issues (project);
CREATE INDEX IF NOT EXISTS idx_issues_parent_issue_id ON issues (parent_issue_id);
CREATE INDEX IF NOT EXISTS idx_issues_assignee ON issues (assignee);
CREATE INDEX IF NOT EXISTS idx_issues_sprint ON issues (sprint);
CREATE INDEX IF NOT EXISTS idx_issues_status ON issues (status);
CREATE INDEX IF NOT EXISTS idx_issues_version ON issues (version);
CREATE INDEX IF NOT EXISTS idx_issues_project_sprint ON issues (project, sprint);
CREATE INDEX IF NOT EXISTS idx_issues_sprint_assignee ON issues (sprint, assignee);

DROP TRIGGER IF EXISTS trg_issues_updated_at ON issues;

CREATE TRIGGER trg_issues_updated_at
BEFORE UPDATE ON issues
FOR EACH ROW
EXECUTE FUNCTION set_updated_at_utc();

CREATE TABLE IF NOT EXISTS sync_runs (
    run_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project TEXT NOT NULL,
    team TEXT NOT NULL,
    sprint TEXT NOT NULL,
    json_path TEXT NOT NULL,
    started_at TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"')),
    finished_at TEXT,
    stats JSONB
);

CREATE INDEX IF NOT EXISTS idx_sync_runs_sprint ON sync_runs (sprint);
CREATE INDEX IF NOT EXISTS idx_sync_runs_started_at ON sync_runs (started_at);

CREATE TABLE IF NOT EXISTS issue_snapshots (
    run_id INTEGER NOT NULL,
    issue_id TEXT NOT NULL,
    project TEXT,
    parent_issue_id TEXT,
    title TEXT NOT NULL,
    assignee TEXT,
    sprint TEXT,
    status TEXT,
    version TEXT,
    description TEXT,
    comments JSONB,
    extra JSONB,
    created_at TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"')),
    updated_at TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"')),
    PRIMARY KEY (run_id, issue_id),
    FOREIGN KEY (run_id) REFERENCES sync_runs (run_id) ON DELETE CASCADE
);

ALTER TABLE issue_snapshots ADD COLUMN IF NOT EXISTS project TEXT;

CREATE INDEX IF NOT EXISTS idx_issue_snapshots_issue_id ON issue_snapshots (issue_id);
CREATE INDEX IF NOT EXISTS idx_issue_snapshots_project ON issue_snapshots (project);
CREATE INDEX IF NOT EXISTS idx_issue_snapshots_parent_issue_id ON issue_snapshots (parent_issue_id);
CREATE INDEX IF NOT EXISTS idx_issue_snapshots_sprint ON issue_snapshots (sprint);
CREATE INDEX IF NOT EXISTS idx_issue_snapshots_project_sprint ON issue_snapshots (project, sprint);
CREATE INDEX IF NOT EXISTS idx_issue_snapshots_status ON issue_snapshots (status);

DROP TRIGGER IF EXISTS trg_issue_snapshots_updated_at ON issue_snapshots;

CREATE TRIGGER trg_issue_snapshots_updated_at
BEFORE UPDATE ON issue_snapshots
FOR EACH ROW
EXECUTE FUNCTION set_updated_at_utc();
`.trim()
